apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce
resources:
  - ../../base
images:
  - name: ghcr.io/YOUR_ORG/auth-service
    newTag: latest
  - name: ghcr.io/YOUR_ORG/catalog-service
    newTag: latest
  - name: ghcr.io/YOUR_ORG/orders-service
    newTag: latest
  - name: ghcr.io/YOUR_ORG/payments-service
    newTag: latest
  - name: ghcr.io/YOUR_ORG/notifications-service
    newTag: latest
