apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: ecommerce
  labels:
    app: payments-service
spec:
  selector:
    app: payments-service
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
